# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devports < Formula
  desc "CLI for managing local development ports and configured service URLs"
  homepage "https://github.com/justyn-clark/devports"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justyn-clark/devports/releases/download/v0.1.5/devports-v0.1.5-darwin-amd64.tar.gz"
      sha256 "1ae4fdaa4e2185f57b6976d7cbbcfad907c0d3bf73a7f7dc6e44ef0909ab57f3"

      define_method(:install) do
        bin.install "devports"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justyn-clark/devports/releases/download/v0.1.5/devports-v0.1.5-darwin-arm64.tar.gz"
      sha256 "170c018ba886f0fa7a99455ac1231b9373c7b75a8a100089fab9687fae897208"

      define_method(:install) do
        bin.install "devports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justyn-clark/devports/releases/download/v0.1.5/devports-v0.1.5-linux-amd64.tar.gz"
      sha256 "3917bc07a7f3da8939675ac94ead292cb9582e8b692420e40edbee07b574cd24"
      define_method(:install) do
        bin.install "devports"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justyn-clark/devports/releases/download/v0.1.5/devports-v0.1.5-linux-arm64.tar.gz"
      sha256 "b34c4fead782bd53a820756e6601fbae19ed000dec9b6cbc83787be2117075f6"
      define_method(:install) do
        bin.install "devports"
      end
    end
  end

  test do
    system "#{bin}/devports", "--version"
  end
end
